-- AlterTable
ALTER TABLE "users" ADD COLUMN "gamesPlayed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN "gamesWon" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN "gamesLost" INTEGER NOT NULL DEFAULT 0;
